### ISSUE TITLE
Azure MS SQL Server - USE statement is not supported to switch between databases

### ISSUE THREAD

**Issue by AllezWiggo** [fluent/fluent-plugin-sql#133]
Hi,
I'm trying to use fluent-plugin-sql with Azure MS SQL Server DB and getting error.

Dockerfile partial config:

```
  && gem install fluent-plugin-sql --no-document \
  && gem install tiny_tds \
  && gem install activerecord-sqlserver-adapter \
```

Error in fluentd logs:

```
  2023-05-12 19:59:57 +0000 [warn]: #0 failed to flush the buffer. retry_times=0 next_retry_time=2023-05-12 19:59:58 +0000 chunk="5fb8489140af6d7034566d69be465982" error_class=TinyTds::Error error="USE statement is not supported to switch between databases. Use a new connection to connect to a different database."
  2023-05-12 19:59:57 +0000 [warn]: #0 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/tiny_tds-2.1.5/lib/tiny_tds/client.rb:60:in `connect'
  2023-05-12 19:59:57 +0000 [warn]: #0 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/tiny_tds-2.1.5/lib/tiny_tds/client.rb:60:in `initialize'
  2023-05-12 19:59:57 +0000 [warn]: #0 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-sqlserver-adapter-7.0.2.0/lib/active_record/connection_adapters/sqlserver_adapter.rb:90:in `new'
  2023-05-12 19:59:57 +0000 [warn]: #0 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-sqlserver-adapter-7.0.2.0/lib/active_record/connection_adapters/sqlserver_adapter.rb:90:in `dblib_connect'
  2023-05-12 19:59:57 +0000 [warn]: #0 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-sqlserver-adapter-7.0.2.0/lib/active_record/connection_adapters/sqlserver_adapter.rb:83:in `new_client'
  2023-05-12 19:59:57 +0000 [warn]: #0 /usr/local/rvm/rubies/ruby-3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-sqlserver-adapter-7.0.2.0/lib/active_record/sqlserver_base.rb:15:in `sqlserver_connection'
```

Looks like Azure SQL Server doesn't support USE command to switch database. Anyone faced and resolved this?
Thanks in advance.

**Comment by jpnwagwu** [comment]
Faced similar issue but not resolved

**Comment by Watson1978** [comment]
Thanks for the report.

This isn't really a bug in the plugin's logic, it's a limitation in how connection options are passed to ActiveRecord for Azure SQL Database.

Root cause:
- Azure SQL Database does not support the `USE` statement to switch databases. Unlike a normal SQL Server instance, each database is logically isolated, so the connection must target the database directly rather than switching to it after connecting.
- `activerecord-sqlserver-adapter` handles this via an `azure: true` connection option (and typically a `user@servername` username format). With that set, it connects straight to the target database instead of issuing `USE`.
- However, this plugin builds a fixed connection config in `start` (`adapter`, `host`, `port`, `database`, `username`, `password`, `socket`, `schema_search_path`, `pool`, `timeout`). There is currently no way to pass extra adapter options such as `azure: true` through the plugin configuration, so the adapter falls back to its default behavior and fails on Azure.

I'm labeling this as an **enhancement**: the plugin should allow passing additional/arbitrary ActiveRecord connection options (a generic pass-through, or at minimum an `azure` flag) so Azure SQL Database and similar setups can be configured.

Workaround until then: since the option can't be supplied via plugin config, you can prepend `configure_connection` (or otherwise force Azure mode) on `activerecord-sqlserver-adapter` from a Ruby initializer loaded before Fluentd starts. Note Azure also generally expects the `username@servername` login format.

Related: #76 (SQL Server connection setup).
