### ISSUE TITLE
Tables and views in schemas are not supported (PostgreSQL)

### ISSUE THREAD

**Issue by static-max** [fluent/fluent-plugin-sql#22]
If I want to use a view thats inside a schema, I get the following error:

    2015-12-11 14:49:10 +0100 [warn]: Can't handle 'data.my-view' table. Ignoring. error="wrong constant name Data.my_view" error_class=NameError
      2015-12-11 14:49:10 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.4.3/lib/fluent/plugin/in_sql.rb:81:in `const_set'
      2015-12-11 14:49:10 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.4.3/lib/fluent/plugin/in_sql.rb:81:in `init'
      2015-12-11 14:49:10 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.4.3/lib/fluent/plugin/in_sql.rb:207:in `block in start'
      2015-12-11 14:49:10 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.4.3/lib/fluent/plugin/in_sql.rb:205:in `reject!'
      2015-12-11 14:49:10 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-0.4.3/lib/fluent/plugin/in_sql.rb:205:in `start'
      2015-12-11 14:49:10 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/root_agent.rb:111:in `block in start'
      2015-12-11 14:49:10 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/root_agent.rb:110:in `each'
      2015-12-11 14:49:10 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/root_agent.rb:110:in `start'

Creating the view in the "public" schema is currently the only workaround I see.

**Comment by repeatedly** [comment]
It seems current ActiveRecord limitation.
Hmm... we need to research how to map schema name to ActiveRecord's model.

**Comment by roligupt** [comment]
are tables and views in a schema supported now? The table i am trying to write the data to is in the schema.

**Comment by roligupt** [comment]
> It seems current ActiveRecord limitation.
> Hmm... we need to research how to map schema name to ActiveRecord's model.

are tables and views in a schema supported now? The table i am trying to write the data to is in the schema.

**Comment by Watson1978** [comment]
This is resolved on `master`.

The crash came from how the input plugin builds an ActiveRecord model class name from the table name. 
It used `table_name.singularize.camelize`, so a schema-qualified name like `data.my-view` became `Data.my_view` — a string containing a dot, which is not a valid Ruby constant name. 
`const_set` therefore raised `NameError: wrong constant name`, and the plugin skipped the table with the "Can't handle ... Ignoring" warning.

The class-name generation now replaces dots with underscores before building the constant, so schema-qualified table names no longer crash at model-creation time:

```ruby
class_name = table_name.gsub(/\./, "_").singularize.camelize
```

For PostgreSQL specifically, the cleaner approach is to set `schema_search_path` to the target schema and then reference the table by its unqualified name:

```
<source>
  @type sql
  host rdb_host
  adapter postgresql
  database rdb_database
  username myuser
  password mypass
  schema_search_path data
  <table>
    table my_view
    tag my_view
  </table>
</source>
```

Closing as resolved. 
If you still hit this on a current release, please open a new issue with your plugin version and the exact table/schema name so we can reproduce it.
