### ISSUE TITLE
Flush failure

### ISSUE THREAD

**Issue by kakoni** [fluent/fluent-plugin-sql#34]
Using master fluentd/this plugin/pg. Database insert isnt working properly, seeing;
```ruby
2016-04-25 23:45:51 +0300 [warn]: fluent/output.rb:331:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2016-04-25 23:45:51 +0300 error_class=Ac
tiveRecord::ConnectionNotEstablished error="No connection pool for ActiveRecord::Base" plugin_id="object:3fc5d5c391ac"
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `ret
rieve_connection'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:87:in `connection'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-import-0.13.0/lib/activerecord-import/adapters/postgresql_adapter.rb:19:in `insert_
many'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-import-0.13.0/lib/activerecord-import/import.rb:496:in `block in import_without_validations_or_callbacks'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-import-0.13.0/lib/activerecord-import/import.rb:494:in `each'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-import-0.13.0/lib/activerecord-import/import.rb:494:in `each_slice'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-import-0.13.0/lib/activerecord-import/import.rb:494:in `import_without_validations_
or_callbacks'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-import-0.13.0/lib/activerecord-import/import.rb:447:in `import_with_validations'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-import-0.13.0/lib/activerecord-import/import.rb:390:in `import_helper'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/gems/activerecord-import-0.13.0/lib/activerecord-import/import.rb:310:in `import'
  2016-04-25 23:45:51 +0300 [warn]: /Users/kakoni/.gem/ruby/2.3.0/bundler/gems/fluent-plugin-sql-c4056247bafc/lib/fluent/plugin/out_sql.rb:98:in `import'
```

**Comment by kakoni** [comment]
Related; https://github.com/zdennis/activerecord-import/issues/272

**Comment by repeatedly** [comment]
From the code, fluent-plugin-sql calls establish_connection before import: https://github.com/fluent/fluent-plugin-sql/blob/c4056247bafc5e60a1bd5ba1d24f2fd816dad650/lib/fluent/plugin/out_sql.rb#L192
Do you know how to solve it?

**Comment by kakoni** [comment]
Wrapping write inside `ActiveRecord::Base.connection_pool.with_connection` should do it
https://github.com/fluent/fluent-plugin-sql/compare/master...kakoni:master#diff-28cdfa34d99998801770f5255936d355

**Comment by repeatedly** [comment]
I tested with each commit of activerecord-import and I found this patch, https://github.com/zdennis/activerecord-import/pull/217, causes this problem.

Hmm... I can't judge your change is correct for all cases.

**Comment by repeatedly** [comment]
I'm not sure why clearing query_cache causes this "No connection pool for ActiveRecord::Base" error...

**Comment by repeatedly** [comment]
I'm now asking other ActiveRecord users about this problem to review your patch.

**Comment by okkez** [comment]
> Wrapping write inside ActiveRecord::Base.connection_pool.with_connection should do it
master...kakoni:master#diff-28cdfa34d99998801770f5255936d355

Looks good to me.
This patch changes behavior related to connection pool.
In previous version, AR uses connection pool.
In his version, AR doesn't use connection pool and always create new connection.

I think this change does not cause performance issue. Because fluent-plugin-sql executes query every few tens of seconds.

**Comment by repeatedly** [comment]
@okkez Thanks for usefule comments :)

@kakoni If you okay, could you send a PR?
