### ISSUE TITLE
Cannot use postgresql adapter

### ISSUE THREAD

**Issue by CheyiLin** [fluent/fluent-plugin-sql#47]
Hi,

I've installed the `pg` gem and set `adapter postgresql`, but got the following errors:
```
fluentd_1  | 2017-04-24 13:15:42 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
fluentd_1  | 2017-04-24 13:15:42 +0000 [info]: starting fluentd-0.12.35
fluentd_1  | 2017-04-24 13:15:42 +0000 [info]: gem 'fluent-plugin-sql' version '0.6.0'
fluentd_1  | 2017-04-24 13:15:42 +0000 [info]: gem 'fluentd' version '0.12.35'
fluentd_1  | 2017-04-24 13:15:42 +0000 [info]: adding match pattern="**" type="stdout"
fluentd_1  | 2017-04-24 13:15:43 +0000 [info]: adding source type="http"
fluentd_1  | 2017-04-24 13:15:43 +0000 [info]: adding source type="sql"
fluentd_1  | 2017-04-24 13:15:43 +0000 [info]: using configuration file: <ROOT>
fluentd_1  |   <source>
fluentd_1  |     @type sql
fluentd_1  |     host my-postgresql-server
fluentd_1  |     database mydb
fluentd_1  |     adapter postgresql
fluentd_1  |     username dbuser
fluentd_1  |     password xxxxxx
fluentd_1  |     tag_prefix mytag
fluentd_1  |     select_interval 2s
fluentd_1  |     select_limit 100
fluentd_1  |     state_file /tmp/fluentd_sql_state
fluentd_1  |     <table>
fluentd_1  |       table logs
fluentd_1  |       tag logs
fluentd_1  |       update_column log_id
fluentd_1  |       time_column created_time
fluentd_1  |     </table>
fluentd_1  |   </source>
fluentd_1  |   <match **>
fluentd_1  |     @type stdout
fluentd_1  |   </match>
fluentd_1  | </ROOT>
fluentd_1  | 2017-04-24 13:15:43 +0000 [info]: shutting down fluentd
fluentd_1  | 2017-04-24 13:15:43 +0000 [info]: shutting down input type="http" plugin_id="object:3fe85d8afacc"
fluentd_1  | 2017-04-24 13:15:43 +0000 [info]: shutting down output type="stdout" plugin_id="object:3fe85d729d74"
fluentd_1  | /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': Could not load 'active_record/connection_adapters/postgresql_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
fluentd_1  |    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/pg-0.20.0/lib/pg.rb:4:in `<top (required)>'
fluentd_1  |    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd_1  |    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:3:in `<top (required)>'
fluentd_1  |    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd_1  |    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:53:in `establish_connection'
fluentd_1  |    from /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-sql-0.6.0/lib/fluent/plugin/in_sql.rb:206:in `start'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:115:in `block in start'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:114:in `each'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:114:in `start'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:237:in `start'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:187:in `run'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:570:in `run_engine'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:162:in `block in start'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:366:in `main_process'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:339:in `block in supervise'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `fork'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `supervise'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:156:in `start'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
fluentd_1  |    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd_1  |    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd_1  |    from /var/lib/gems/2.3.0/gems/fluentd-0.12.35/bin/fluentd:5:in `<top (required)>'
fluentd_1  |    from /usr/local/bin/fluentd:22:in `load'
fluentd_1  |    from /usr/local/bin/fluentd:22:in `<main>'
fluentd_1  | 2017-04-24 13:15:43 +0000 [info]: process finished code=256
fluentd_1  | 2017-04-24 13:15:43 +0000 [warn]: process died within 1 second. exit.
```

And the `fluent-gem list` result is:
```
activemodel (5.0.2, 4.2.8)
activerecord (5.0.2, 4.2.8)
activerecord-import (0.18.1)
activerecord-postgresql-adapter (0.0.1)
activerecord-sqlserver-adapter (5.0.7)
activesupport (5.0.2, 4.2.8)
arel (7.1.4, 6.0.4)
bigdecimal (1.2.8)
builder (3.2.3)
concurrent-ruby (1.0.5)
cool.io (1.5.0)
did_you_mean (1.0.0)
fluent-plugin-sql (0.6.0)
fluentd (0.12.35)
http_parser.rb (0.6.0)
i18n (0.8.1)
io-console (0.4.5)
json (2.1.0, 1.8.3)
mini_portile2 (2.1.0)
minitest (5.9.0)
msgpack (1.1.0)
net-telnet (0.1.1)
oj (2.18.5)
pg (0.20.0)
power_assert (0.2.7)
psych (2.1.0)
rake (10.5.0)
rdoc (4.2.1)
sigdump (0.2.4)
string-scrub (0.0.5)
test-unit (3.1.7)
thread_safe (0.3.6)
tiny_tds (1.3.0)
tzinfo (1.2.3)
tzinfo-data (1.2017.2)
yajl-ruby (1.3.0)
```

Is there something I missed? Thanks.

**Comment by repeatedly** [comment]
How about removing `activerecord-postgresql-adapter` from gem?

**Comment by CheyiLin** [comment]
Just found the problem ...

In the Dockerfile I removed the build dependencies including `libpq-dev` after gem `pg` installed, that's why the plugin can't load the postgresql adapter.

Thanks for the reply anyway.
