### ISSUE TITLE
pg Gem Load Error

### ISSUE THREAD

**Issue by anuragensemble** [fluent/fluent-plugin-sql#56]
`2018-02-05 10:44:33 +0000 [info]: starting fluentd-1.0.2 pid=11304 ruby="2.4.2"
2018-02-05 10:44:33 +0000 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/opt/td-agent/embedded/bin/fluentd", "--log", "/var/log/td-agent/td-agent.log", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2018-02-05 10:44:33 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.4.0'
2018-02-05 10:44:33 +0000 [info]: gem 'fluent-plugin-kafka' version '0.6.5'
2018-02-05 10:44:33 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.0.1'
2018-02-05 10:44:33 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.0'
2018-02-05 10:44:33 +0000 [info]: gem 'fluent-plugin-sql' version '0.6.1'
2018-02-05 10:44:33 +0000 [info]: gem 'fluent-plugin-td' version '1.0.0'
2018-02-05 10:44:33 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.3'
2018-02-05 10:44:33 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.2'
2018-02-05 10:44:33 +0000 [info]: gem 'fluentd' version '1.0.2'
2018-02-05 10:44:33 +0000 [info]: adding match pattern="logfile" type="sql"
2018-02-05 10:44:33 +0000 [info]: adding match pattern="td.*.*" type="tdlog"
2018-02-05 10:44:33 +0000 [warn]: #0 secondary type should be same with primary one primary="Fluent::Plugin::TreasureDataLogOutput" secondary="Fluent::Plugin::FileOutput"
2018-02-05 10:44:33 +0000 [info]: adding match pattern="debug.**" type="stdout"
2018-02-05 10:44:33 +0000 [info]: adding source type="tail"
2018-02-05 10:44:33 +0000 [info]: adding source type="forward"
2018-02-05 10:44:33 +0000 [info]: adding source type="http"
2018-02-05 10:44:33 +0000 [info]: adding source type="debug_agent"
2018-02-05 10:44:33 +0000 [info]: #0 starting fluentd worker pid=11315 ppid=11310 worker=0
2018-02-05 10:44:33 +0000 [error]: #0 unexpected error error_class=Gem::LoadError error="Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord)."
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:50:in `establish_connection'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activerecord-import-0.22.0/lib/activerecord-import/import.rb:205:in `establish_connection_with_activerecord_import'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-sql-0.6.1/lib/fluent/plugin/out_sql.rb:202:in `start'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:165:in `block in start'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:153:in `each'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:140:in `each'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:164:in `start'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:274:in `start'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:219:in `run'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:774:in `run_engine'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:523:in `block in run_worker'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:699:in `main_process'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:518:in `run_worker'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/bin/fluentd:8:in `<top (required)>'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2018-02-05 10:44:33 +0000 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
2018-02-05 10:44:33 +0000 [error]: #0 Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). path=nil error_class=Gem::LoadError error="Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord)."
  2018-02-05 10:44:33 +0000 [error]: #0 suppressed same stacktrace
2018-02-05 10:44:34 +0000 [info]: Worker 0 finished unexpectedly with status 2
2018-02-05 10:44:34 +0000 [info]: Received graceful stop`

**Comment by anuragensemble** [comment]
The version of pg gem was incorrect.

**Comment by Oleg2tor** [comment]
So which one is correct? Have same issue.

**Comment by Oleg2tor** [comment]
Found solution here https://github.com/fluent/fluent-plugin-sql/issues/47
