### ISSUE TITLE
cannot load such file -- fluent/plugin/output

### ISSUE THREAD

**Issue by eelke-at-bolt** [fluent/fluent-plugin-sql#66]
Hello,

I have an ubuntu 18.04 machine and installed td-agent with
http://toolbelt.treasuredata.com/sh/install-ubuntu-precise-td-agent2.sh
and installed the plugin and database gem with
td-agent-gem install fluent-plugin-sql --no-document
td-agent-gem install pg -v 0.21.0 --no-document

First tested with output to file which works. Then added config for output to postgresql

```
<match web01.php-fpm.access>
  @type sql
  database fluent
  username td-agent
  adapter postgresql
  
  <table>
  table phpfpm_access
  column_mapping 'timestamp:ts,req,status,script,dur,mem,cpu'
  </table>
</match>
```

When i did td-agent --dry-run I get error:

```
2018-12-19 14:51:28 +0100 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2018-12-19 14:51:28 +0100 [info]: starting fluentd-0.12.40 as dry run mode
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-plugin-kafka' version '0.6.1'
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-plugin-mongo' version '0.8.1'
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.6'
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-plugin-s3' version '0.8.5'
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-plugin-sql' version '1.0.0'
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-plugin-td' version '0.10.29'
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.3'
2018-12-19 14:51:28 +0100 [info]: gem 'fluent-plugin-webhdfs' version '0.7.1'
2018-12-19 14:51:28 +0100 [info]: gem 'fluentd' version '0.12.40'
2018-12-19 14:51:28 +0100 [info]: adding match pattern="td.*.*" type="tdlog"
2018-12-19 14:51:28 +0100 [info]: adding match pattern="debug.**" type="stdout"
2018-12-19 14:51:28 +0100 [info]: adding match pattern="web01.php-fpm.access" type="sql"
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fluent/plugin/output (LoadError)
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sql-1.0.0/lib/fluent/plugin/out_sql.rb:1:in `<top (required)>'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:173:in `block in try_load_plugin'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:170:in `each'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:170:in `try_load_plugin'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:130:in `new_impl'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:59:in `new_output'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/agent.rb:131:in `add_match'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/agent.rb:64:in `block in configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/agent.rb:57:in `each'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/agent.rb:57:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/root_agent.rb:86:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/engine.rb:129:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/engine.rb:103:in `run_configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:489:in `run_configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:200:in `dry_run'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:147:in `start'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/bin/fluentd:5:in `<top (required)>'
        from /opt/td-agent/embedded/bin/fluentd:23:in `load'
        from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
        from /usr/sbin/td-agent:7:in `load'
        from /usr/sbin/td-agent:7:in `<main>'

```

**Comment by repeatedly** [comment]
If you use bionic with older td-agent, please use td-agent 2.5 instead of td-agent 2.

http://toolbelt.treasuredata.com/sh/install-ubuntu-bionic-td-agent2.5.sh

We don't guarantee the compatibility between precise and bionic.

**Comment by She1d0n** [comment]
> Sorry my bad, should have installed older version of plugin as td-agent is 0.12
> 
> td-agent-gem install fluent-plugin-sql -v 0.6.1 --no-document

Have you solved it by chagen version？
I meet this error again. My fluent-plugin-sql is 1.0.0,my fluent is 2.5.2.

**Comment by eelke-at-bolt** [comment]
Don't remember exactly but looking at the server and my notes I last seem to have switched to td-agent 3. Installed it using following script

`https://toolbelt.treasuredata.com/sh/install-ubuntu-bionic-td-agent3.sh`

Then installed plugin with 

`td-agent-gem install fluent-plugin-sql --no-document`
`td-agent-gem install pg -v 0.21.0 --no-document`
