### ISSUE TITLE
Cannot use with fluentd-1.7

### ISSUE THREAD

**Issue by ashie** [fluent/fluent-plugin-sql#77]
fluent-plugin-sql cannot use with fluentd-1.7 due to conflicting tzinfo versions (as mentioned in https://github.com/fluent/fluentd/issues/2634).

* fluentd-1.7 requires tzinfo 2.0
* fluent-plugin-sql requires tzinfo 1.1 via ActiveSupport

```
2019-10-15 14:22:24 +0900 [info]: parsing config file is succeeded path="conf/fluent.conf"
2019-10-15 14:22:24 +0900 [info]: adding forwarding server '192.168.0.12:24224' host="192.168.0.12" port=24224 weight=60 plugin_id="object:2ab07d33ebd8"
2019-10-15 14:22:24 +0900 [info]: [forward_output] adding forwarding server '192.168.0.11:24224' host="192.168.0.11" port=24224 weight=60 plugin_id="forward_output"
2019-10-15 14:22:24 +0900 [info]: [http_input] Oj is not installed, and failing back to Yajl for json parser
Traceback (most recent call last):
	35: from /usr/local/bin/fluentd:23:in `<main>'
	34: from /usr/local/bin/fluentd:23:in `load'
	33: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/bin/fluentd:8:in `<top (required)>'
	32: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	31: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	30: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/command/fluentd.rb:314:in `<top (required)>'
	29: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/supervisor.rb:504:in `run_supervisor'
	28: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/supervisor.rb:599:in `supervise'
	27: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/supervisor.rb:581:in `dry_run'
	26: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/supervisor.rb:804:in `run_configure'
	25: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/engine.rb:96:in `run_configure'
	24: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/engine.rb:131:in `configure'
	23: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:156:in `configure'
	22: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:156:in `each'
	21: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:160:in `block in configure'
	20: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/root_agent.rb:315:in `add_source'
	19: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/plugin.rb:100:in `new_input'
	18: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/plugin.rb:146:in `new_impl'
	17: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/registry.rb:44:in `lookup'
	16: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/registry.rb:99:in `search'
	15: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/registry.rb:99:in `each'
	14: from /var/lib/gems/2.5.0/gems/fluentd-1.7.3/lib/fluent/registry.rb:102:in `block in search'
	13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	11: from /var/lib/gems/2.5.0/gems/fluent-plugin-sql-1.1.1/lib/fluent/plugin/in_sql.rb:21:in `<top (required)>'
	10: from /var/lib/gems/2.5.0/gems/fluent-plugin-sql-1.1.1/lib/fluent/plugin/in_sql.rb:23:in `<module:Plugin>'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	 7: from /usr/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
	 6: from /usr/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
	 5: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	 4: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	 3: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	 2: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
	 1: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
/usr/lib/ruby/2.5.0/rubygems/specification.rb:2327:in `raise_if_conflicts': Unable to activate activesupport-5.2.3, because tzinfo-2.0.0 conflicts with tzinfo (~> 1.1) (Gem::ConflictError)
```

**Comment by ganmacs** [comment]
https://github.com/fluent/fluentd/pull/2673
